name: commissars-digest
region: nyc
services:
  - name: web
    github:
      repo: supercake53/commissars-digest
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npx serve web-build -l 8080
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: ${API_URL}
    health_check:
      http_path: /
      port: 8080
    cors:
      allow_origins:
        - "*.digitalocean.app"
        - "localhost:19006" 